//ADDING/REMOVING INGREDIENTS
export const ADD_INGREDIENTS = "ADD_INGREDIENTS"
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS" 
export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const SET_ERROR_FAILED = "SET_ERROR_FAILED"

//ORDER RELATED

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START"
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS"
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL"
export const PURCHASE_INIT = 'PURCHASE_INIT'


